version: "3.9"

services:

  db:
    image: postgres:11
    restart: always
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: LeaveRequest
    command: >
        sh -c "  python3 manage.py makemigrations --noinput && \
                 python3 manage.py migrate --noinput && \
                 python3 manage.py collectstatic --noinput && \
                 python3 manage.py createsuperuser --username superuser --email admin@localhost --noinput; \
                 gunicorn leave.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    volumes:
      - ./web:/web
    depends_on:
      - db
  
volumes:
  pgdata: