version: "3.9"

services:
  web:
    build: 
      context: .
    container_name: LeaveRequest
    command: >
      sh -c "python3 manage.py makemigrations --noinput && \
                 python3 manage.py migrate --noinput && \
                 python3 manage.py collectstatic --noinput && \
                 python3 manage.py createsuperuser --username superuser --email admin@localhost --noinput; \
                 python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./web:/web
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - pgdata:/var/lib/posgresql/data
volumes:
  pgdata: