# Generated by Django 4.1.1 on 2022-10-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reply_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.RemoveField(
            model_name='reply',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='end',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='start',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='updated',
        ),
    ]
