# Generated by Django 4.1.2 on 2022-10-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reply_options_remove_reply_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
